#!/bin/sh
#------------------------------
#
# tools/parseSaleae/aa
#
#------------------------------


# printf "\n\nCSV \n\n"
make --quiet -C ~/libs/csv
rc=$?

if [ $rc -ne 0 ] ; then
    set-title Error building libs/csv
    exit 1;
fi





# printf "\n\nCSV \n\n"
(
    cd ~/libs/gdb

    ./aa
    rc=$?

    if [ $rc -ne 0 ] ; then
	set-title Error building libs/gdb
	exit 1;
    fi
)

if [ ! -d build ] ; then
    cmake -S . -B build -DCMAKE_BUILD_TYPE=DEBUG
fi





LOG=/tmp/parseSaleae.log

rm -f $LOG

date > $LOG
cmake --build build --parallel 4 # >>$LOG 2>&1
rc=$?

if [ $rc -eq 0 ] ; then
    rm -f $LOG
else
    if [ -r $LOG ] ; then
	#	clear
	head $LOG
	wc $LOG
    fi
    set-title Error
    exit 1
fi

if [ ! -r parseSaleae ] ; then
    ln -s build/parseSaleae
fi

# make --quiet
make

date
