#!/bin/sh

# clear

# printf "\n\nCSV \n\n"
make --quiet -C ~/libs/csv
rc=$?

if [ $rc -ne 0 ] ; then
    set-title Error building libs/csv
    exit 1;
fi

# printf "\n\nPARSE_LCD \n\n"
# make --quiet RSYNC

if [ ! -d build ] ; then
    cmake -S . -B build -DCMAKE_BUILD_TYPE=DEBUG
fi

cmake --build build --parallel 2  #   >/tmp/compile.lst 2>&1
rc=$?

if [ $rc -ne 0 ] ; then
    set-title Error
    exit 1
fi

if [ ! -r parseSaleae ] ; then
    ln -s build/parseSaleae
fi

# make --quiet
make

# make joins.lst

date
